schema: 1
type: policy-context

id: elasticsearch-domain-is-not-configured-with-https
name: Elasticsearch domain is not configured with HTTPS
labels:
  - contextualization

csp: aws
service: elasticsearchService
resource-type: domain

class: risk
subclass: config
category: networking
subcategory: encryption

filters:
  - vendor: prisma-cloud
    policies:
      - 0dfd7218-7605-4323-a143-8204ca83faea
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "0dfd7218-7605-4323-a143-8204ca83faea"
  - vendor: checkov
    policies:
      - CKV_AWS_83
    match-type: any
    rules:
      - .vendorId == "checkov" and .vendorPolicy == "CKV_AWS_83"

risk-config:
  default-risk: medium
