schema: 1
type: policy-context

id: cloudfront-viewer-protocol-policy-is-not-configured-with-https
name: CloudFront viewer protocol policy is not configured with HTTPS
labels:
  - contextualization

csp: aws
service: cloudfront
resource-type: distribution

class: risk
subclass: config
category: networking
subcategory: encryption

filters:
  - vendor: aws-config
    policies:
      - cloudfront-viewer-policy-https
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("cloudfront-viewer-policy-https"))
  - vendor: prisma-cloud
    policies:
      - d183c5cd-6fe6-43a9-8fbf-6b4e44c84ec9
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "d183c5cd-6fe6-43a9-8fbf-6b4e44c84ec9"
  - vendor: checkov
    policies:
      - CKV_AWS_34 
    match-type: any
    rules:
      - .vendorId == "checkov" and .vendorPolicy == "CKV_AWS_34"

risk-config:
  default-risk: high
