schema: 1
type: policy-context

id: shield-drt-access-role-is-not-configured
name: Shield DDoS response team (DRT) access role is not configured
labels:
  - contextualization

csp: aws
service: shield
resource-type: protection

class: risk
subclass: config
category: iam
subcategory: authorization

filters:
  - vendor: aws-config
    policies:
      - shield-drt-access
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("shield-drt-access"))

risk-config:
  default-risk: ""
