schema: 1
type: policy-context

id: clb-is-in-use-for-internet-facing-applications
name: Classic Load Balancer (CLB) is in use for internet-facing applications
labels:
  - contextualization

csp: aws
service: elb
resource-type: loadbalancer

class: risk
subclass: config
category: visibility
subcategory: hygiene

filters:
  - vendor: prisma-cloud
    policies:
      - 72859f28-0817-43d2-b249-1a9350e5aa89
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "72859f28-0817-43d2-b249-1a9350e5aa89"

risk-config:
  default-risk: low
