schema: 1
type: policy-context

id: sql-server-ads-vulnerability-assessment-is-misconfigured
name: SQL Server ADS Vulnerability Assessment is misconfigured
labels:
  - contextualization

csp: azure
service: Microsoft.Sql
resource-type: servers/vulnerabilityAssessments

class: risk
subclass: config
category: visibility
subcategory: monitoring

filters:
  - vendor: prisma-cloud
    policies:
      - b805e5f2-8479-4197-82ce-9d8fcdf38a44 # ADS Vulnerability Assessment is disabled
      - 2d9ff413-f69f-484e-ba55-22ab6333c249 # 'Also send email notifications to admins and subscription owners' is disabled
      - aa62cb1d-2bcb-478b-af5c-62462f8a6cba # Periodic recurring scans is disabled
      - bfff252d-3f21-4115-978d-e1a48d8ae19c # 'Send scan reports to' is not configured
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "b805e5f2-8479-4197-82ce-9d8fcdf38a44"
      - .vendorId == "prisma-cloud" and .vendorPolicy == "2d9ff413-f69f-484e-ba55-22ab6333c249"
      - .vendorId == "prisma-cloud" and .vendorPolicy == "aa62cb1d-2bcb-478b-af5c-62462f8a6cba"
      - .vendorId == "prisma-cloud" and .vendorPolicy == "bfff252d-3f21-4115-978d-e1a48d8ae19c"

risk-config:
  default-risk: medium
