schema: 1
type: policy-context

id: cloudtrail-is-not-configured-in-multiple-regions
name: CloudTrail is not configured in multiple regions
labels:
  - contextualization

csp: aws
service: cloudtrail
resource-type: trail

class: risk
subclass: config
category: visibility
subcategory: logging

filters:
  - vendor: aws-config
    policies:
      - "multi-region-cloudtrail-enabled"
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("multi-region-cloudtrail-enabled"))
  - vendor: prisma-cloud
    policies:
      - "36a5345a-230d-438e-a04c-a287a513e3dc"
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "36a5345a-230d-438e-a04c-a287a513e3dc"
  - vendor: checkov
    policies:
      - CKV_AWS_67
    match-type: any
    rules:
      - .vendorId == "checkov" and .vendorPolicy == "CKV_AWS_67"

risk-config:
  default-risk: critical
