schema: 1
type: policy-context

id: instance-is-not-configured-with-imdsv2
name: EC2 instance is not configured with Instance Metadata Service v2 (IMDSv2)
labels:
  - contextualization

csp: aws
service: ec2
resource-type: instance

class: risk
subclass: config
category: iam
subcategory: authentication

filters:
  - vendor: aws-config
    policies:
      - ec2-imdsv2-check
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("ec2-imdsv2-check"))
  - vendor: prisma-cloud
    policies:
      - 32f75d19-c34d-4ec5-aa8c-675959db3aad
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "32f75d19-c34d-4ec5-aa8c-675959db3aad"
  - vendor: checkov
    policies: 
      - CKV_AWS_79 #IMDSv1 enabled in instance's launch template
    match-type: any
    rules:
      - .vendorId == "checkov" and .vendorPolicy == "CKV_AWS_79"

risk-config:
  default-risk: medium
