schema: 1
type: policy-context

id: app-service-app-network-encryption-issue
name: App Service app network encryption issue
labels:
  - contextualization

csp: azure
service: Microsoft.Web
resource-type: sites/networkConfig

class: risk
subclass: config
category: networking
subcategory: encryption

filters:
  - vendor: prisma-cloud
    policies:
      - 7cc2b77b-ad71-4a84-8cab-66b2b04eea5f # Web app does not redirect HTTP to HTTPS
      - 74e43b65-16bf-42a5-8d10-a0f245716cde # Web app does not use latest TLS version
      - 46d8388d-72e4-413c-9a44-3670df42cfea # Function app does not redirect HTTP to HTTPS
      - 7c24e2c1-3ef1-49bf-aaf4-f1a8e5459186 # Function app does not use latest TLS version
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "7cc2b77b-ad71-4a84-8cab-66b2b04eea5f"

risk-config:
  default-risk: medium
